#person:
#  lastName: 李旺红
#  age: 24
#  boss: false
#  birth: 2018/12/12
#  map: {k1: v1,k2: v2}
#  list:
#    - lwh
#    - xcj
#  dog:
#    name: 严海斌
#    age: 12

server:
  port: 8081
spring:
  profiles:
    active: prod
---


server:
  port: 8083
spring:
  profiles: dev


---
server:
  port: 8085
spring:
  profiles: prod